найти всех студентов, у которых ЕГЭ по русскому больше ЕГЭ по математике (не сильно ли много таких? ))))))

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('data_csv.csv', sep=';')

print(df[(df['EGEruss'] > df['EGEmath'])]) #Много

    sex  age  growth       birth  EGEmath  EGEruss  EGEphis    s1    s2    s3  \
0     0   19     173  14.05.1996       56       67       47   3,6   3,6   3,5
4     0   19     161  25.10.1996       75       79       59   4,7     5     5
6     1   19     175  20.05.1996       56       90       42     3     3  2,75
7     0   21     164  13.09.1994       68       95       50   3,5   3,5  3,25
9     1   20     177  31.12.1995       63       67       73     3     3     3
11    0   20     165  16.05.1995       63       66       43   3,5  3,25  3,75
13    1   21     198  07.11.1993       57       62       63   3,4   3,4   3,4
14    0   21     170  02.04.1994       70       92       60     3  3,25  4,25
17    0   21     173  17.12.1994       66       69       53     3     3     4
18    0   20     152  19.06.1995       50       72       50     3     3     3
19    0   21     175  15.02.1995       92       94       88     5     5     5
21    1   21     187  18.12.1994       74       87       75  3,25  3,25   3,5
23    0   20     155  18.01.1996       68       79       53     3  3,25     3
24    1   21     177  01.04.1995       42       90       68     3     3     3
25    0   22     169  02.04.1994       70       92       59     3  3,25  4,25
30    1   20     173  25.06.1994       67       81       72     3     4     3
31    0   20     156  05.03.1996       60       90       46   3,5   3,5   3,5
32    1   19     188  10.06.1996       70       73       54     3     4     3
34    1   19     173  12.01.1997       75       82       60   4,6     5     5
37    1   19     177  02.09.1996       80       84       57     4   4,3   4,5
39    0   19     165  19.09.1996       53       60       60     3     3     3
41    0   19     161  27.10.1996       60       70       41     3     3     3
47    0   19     165  11.08.1996       73       79       58   4,3   4,3   4,8
48    0   19     168  08.02.1997       75       88       57     3   3,7     5
49    0   19     169  08.06.1996       56       65       54   3,5   3,5   3,5
50    0   20     160  14.03.1996       52       69       57   3,5   3,5   3,5
52    0   19     161  25.10.1996       75       79       59   4,9   4,9   4,9
54    0   19     173  14.05.1996       56       67       47   3,6   3,6   3,5
55    0   19     160  15.07.1996       56       76       49   3,7     3  3,75
57    0   18     159  18.12.1997       78       95       73   4,3     0     0

     ...   yes3 yes4 yes5 yes6  yes7  hostel  duration  course  coin  stones
0    ...      0    0    0    0     0       0        15       2     1       2
4    ...      1    0    0    0     0       0        30       2     1       1
6    ...      0    0    0    0     0       0        30       2     1       1
7    ...      0    0    0    0     0       1        60       3     1       1
9    ...      0    0    0    0     0       0        15       2     0       0
11   ...      0    1    1    1     1       0        40       4     0       1
13   ...      0    1    1    0     0       0        20       4     0       1
14   ...      1    0    1    1     1       0        25       4     0       1
17   ...      1    1    0    1     1       0        90       4     1       0
18   ...      0    0    0    0     0       0        60       3     0       0
19   ...      1    1    1    0     0       0        30       3     0       1
21   ...      0    0    0    0     0       0        60       3     0       2
23   ...      0    0    0    0     0       0        13       3     0       1
24   ...      0    0    0    0     0       0        20       3     1       2
25   ...      1    0    1    1     1       0        25       4     1       1
30   ...      0    0    0    0     0       0        60       3     1       2
31   ...      0    0    0    0     0       1        10       2     0       1
32   ...      0    0    0    0     0       0        60       2     0       1
34   ...      1    0    0    0     0       0        60       2     0       1
37   ...      1    0    0    0     0       0        10       2     0       1
39   ...      0    0    0    0     0       0        25       2     1       1
41   ...      0    0    0    0     0       0        90       2     0       0
47   ...      1    0    0    0     0       0        30       2     0       0
48   ...      1    0    0    0     0       0        60       2     0       0
49   ...      0    0    0    0     0       1        15       2     0       1
50   ...      0    0    0    0     0       1        15       2     0       1
52   ...      1    0    0    0     0       0        40       2     1       1
54   ...      0    0    0    0     0       0        15       2     1       1
55   ...      0    0    0    0     0       0        15       2     0       1
57   ...      0    0    0    0     0       0        75       1     0       1

[30 rows x 26 columns]

найти сумму баллов по трем экзаменам ЕГЭ для мужчин и для женщин. Какой пол в среднем имеет лучшую сумму балов? Подумайте над оптимальным порядком суммирования здесь.

In [31]:
print("Способ 1")
m = df[(df['sex'] == 1)]
w = df[(df['sex'] == 0)]
print(m)
print(w)
mean_m = m['EGEmath'].mean() + m['EGEruss'].mean() + m['EGEphis'].mean()
mean_w = w['EGEmath'].mean() + w['EGEruss'].mean() + w['EGEphis'].mean()
print("M")
print(mean_m)
print("W")
print(mean_w)

print("Способ 2")
EGEmath_m = m['EGEmath'].values
EGEruss_m = m['EGEruss'].values
EGEphis_m = m['EGEphis'].values

EGEmath_w = w['EGEmath'].values
EGEruss_w = w['EGEruss'].values
EGEphis_w = w['EGEphis'].values

count_m = np.size(EGEmath_m)
count_w = np.size(EGEmath_w)

sum_m = np.zeros(count_m, int)
sum_w = np.zeros(count_w, int)

for i in range(0, count_m):
    sum_m[i] = EGEmath_m[i] + EGEruss_m[i] + EGEphis_m[i]
    
for i in range(0, count_w):
    sum_w[i] = EGEmath_w[i] + EGEruss_w[i] + EGEphis_w[i]

print("Sum m")
print(sum_m)
print("Sum w")
print(sum_w)
    
print("M")
print(sum_m.mean())
print("W")
print(sum_w.mean())
print("Median M")
print(np.median(sum_m))
print("Median W")
print(np.median(sum_w))

Способ 1
    sex  age  growth       birth  EGEmath  EGEruss  EGEphis    s1    s2    s3  \
1     1   19     182  22.08.1996       50       50       49     3     3     4
2     1   20     193  13.10.1995       67       62       58   4,5     4  3,25
5     1   20     186  23.01.1996       64       64       36     4     4     2
6     1   19     175  20.05.1996       56       90       42     3     3  2,75
8     1   20     168  07.07.1995       94       92       91     5  4,75     5
9     1   20     177  31.12.1995       63       67       73     3     3     3
12    1   20     169  17.01.1996       96       73       79   3,4   3,4   3,4
13    1   21     198  07.11.1993       57       62       63   3,4   3,4   3,4
15    1   20     177  01.04.1995       67       67       66   3,2   3,5   3,2
21    1   21     187  18.12.1994       74       87       75  3,25  3,25   3,5
22    1   20     170  01.01.1996       74       70       70   3,9   3,9   3,9
24    1   21     177  01.04.1995       42       90       68     3     3     3
26    1   20     185  14.05.1995       80       80       70   3,5   3,5  3,75
27    1   20     181  18.03.1996       71       70       59  4,67  4,33  4,67
29    1   21     180  06.03.1995       70       63       60  3,75   4,5     4
30    1   20     173  25.06.1994       67       81       72     3     4     3
32    1   19     188  10.06.1996       70       73       54     3     4     3
33    1   22     176  12.06.1993       62       61       58   3,5     3  3,25
34    1   19     173  12.01.1997       75       82       60   4,6     5     5
35    1   19     181  16.01.1996       81       69       73   4,3   4,3   4,5
37    1   19     177  02.09.1996       80       84       57     4   4,3   4,5
38    1   29     188  06.10.1995       64       45       40     3     3     3
40    1   19     189  29.04.1996       80       62       61   3,7   3,7   3,7
42    1   19     166  12.04.1996       67       60       60     3     3     3
43    1   19     192  22.06.1996       60       60       47     3     3     3
44    1   19     183  22.11.1996       70       70       49     3     3  3,25
46    1   19     192  24.12.1996       80       69       59     3     3     3
51    1   21     185  08.02.1995       73       71       53     4     3     3
56    1   18     183  13.11.1997       74       69       52     3     0     0
58    1   18     182  04.09.1997       70       66       65   4,3     0     0

     ...   yes3 yes4 yes5 yes6  yes7  hostel  duration  course  coin  stones
1    ...      1    0    0    0     0       0        90       2     0       0
2    ...      1    0    0    0     0       0        15       2     0       0
5    ...      0    0    0    0     0       1        15       2     0       0
6    ...      0    0    0    0     0       0        30       2     1       1
8    ...      1    1    0    0     0       0        30       3     0       1
9    ...      0    0    0    0     0       0        15       2     0       0
12   ...      0    1    0    0     0       0        15       3     0       0
13   ...      0    1    1    0     0       0        20       4     0       1
15   ...      0    0    0    0     0       0        20       3     0       0
21   ...      0    0    0    0     0       0        60       3     0       2
22   ...      1    1    0    0     0       0        60       3     0       1
24   ...      0    0    0    0     0       0        20       3     1       2
26   ...      0    0    0    0     0       1        15       3     1       2
27   ...      1    0    0    0     0       0        30       2     1       0
29   ...      1    1    0    0     0       0        40       3     1       2
30   ...      0    0    0    0     0       0        60       3     1       2
32   ...      0    0    0    0     0       0        60       2     0       1
33   ...      0    0    0    0     1       0        20       4     0       1
34   ...      1    0    0    0     0       0        60       2     0       1
35   ...      1    0    0    0     0       0        50       2     0       0
37   ...      1    0    0    0     0       0        10       2     0       1
38   ...      0    0    0    0     0       0        60       2     0       0
40   ...      1    0    0    0     0       0        70       2     0       0
42   ...      0    0    0    0     0       0        40       2     1       2
43   ...      0    0    0    0     0       0        60       2     0       1
44   ...      0    0    0    0     0       0        12       2     1       2
46   ...      0    0    0    0     0       0        45       2     0       0
51   ...      0    0    0    0     0       0        75       2     0       0
56   ...      0    0    0    0     0       0        15       1     1       1
58   ...      0    0    0    0     0       0        60       2     1       1

[30 rows x 26 columns]
    sex  age  growth       birth  EGEmath  EGEruss  EGEphis   s1    s2    s3  \
0     0   19     173  14.05.1996       56       67       47  3,6   3,6   3,5
3     0   20     160  01.09.1995       70       54       46    3     3     3
4     0   19     161  25.10.1996       75       79       59  4,7     5     5
7     0   21     164  13.09.1994       68       95       50  3,5   3,5  3,25
10    0   21     168  02.02.1995       77       70       60    4   4,5     4
11    0   20     165  16.05.1995       63       66       43  3,5  3,25  3,75
14    0   21     170  02.04.1994       70       92       60    3  3,25  4,25
16    0   22     178  01.01.1994       60       56       65    4   4,5     4
17    0   21     173  17.12.1994       66       69       53    3     3     4
18    0   20     152  19.06.1995       50       72       50    3     3     3
19    0   21     175  15.02.1995       92       94       88    5     5     5
20    0   20     165  25.03.1996       95       85       95    5     5     5
23    0   20     155  18.01.1996       68       79       53    3  3,25     3
25    0   22     169  02.04.1994       70       92       59    3  3,25  4,25
28    0   21     168  02.02.1995       77       70       67    4   4,5  4,25
31    0   20     156  05.03.1996       60       90       46  3,5   3,5   3,5
36    0   20     158  20.01.1996       75       70       70    4   4,3     4
39    0   19     165  19.09.1996       53       60       60    3     3     3
41    0   19     161  27.10.1996       60       70       41    3     3     3
45    0   19     159  15.06.1996       90       82       92    4   4,3     4
47    0   19     165  11.08.1996       73       79       58  4,3   4,3   4,8
48    0   19     168  08.02.1997       75       88       57    3   3,7     5
49    0   19     169  08.06.1996       56       65       54  3,5   3,5   3,5
50    0   20     160  14.03.1996       52       69       57  3,5   3,5   3,5
52    0   19     161  25.10.1996       75       79       59  4,9   4,9   4,9
53    0   19     158  16.05.1996       80       68       53  4,6   4,8   4,8
54    0   19     173  14.05.1996       56       67       47  3,6   3,6   3,5
55    0   19     160  15.07.1996       56       76       49  3,7     3  3,75
57    0   18     159  18.12.1997       78       95       73  4,3     0     0

     ...   yes3 yes4 yes5 yes6  yes7  hostel  duration  course  coin  stones
0    ...      0    0    0    0     0       0        15       2     1       2
3    ...      0    0    0    0     0       0        20       2     0       1
4    ...      1    0    0    0     0       0        30       2     1       1
7    ...      0    0    0    0     0       1        60       3     1       1
10   ...      0    1    0    0     0       0        60       3     0       1
11   ...      0    1    1    1     1       0        40       4     0       1
14   ...      1    0    1    1     1       0        25       4     0       1
16   ...      1    1    1    1     1       0        90       4     0       0
17   ...      1    1    0    1     1       0        90       4     1       0
18   ...      0    0    0    0     0       0        60       3     0       0
19   ...      1    1    1    0     0       0        30       3     0       1
20   ...      1    1    1    0     0       0        20       3     0       1
23   ...      0    0    0    0     0       0        13       3     0       1
25   ...      1    0    1    1     1       0        25       4     1       1
28   ...      0    1    0    0     0       0        40       3     0       1
31   ...      0    0    0    0     0       1        10       2     0       1
36   ...      0    0    0    0     0       1        15       2     0       2
39   ...      0    0    0    0     0       0        25       2     1       1
41   ...      0    0    0    0     0       0        90       2     0       0
45   ...      0    0    0    0     0       0        75       2     0       1
47   ...      1    0    0    0     0       0        30       2     0       0
48   ...      1    0    0    0     0       0        60       2     0       0
49   ...      0    0    0    0     0       1        15       2     0       1
50   ...      0    0    0    0     0       1        15       2     0       1
52   ...      1    0    0    0     0       0        40       2     1       1
53   ...      1    0    0    0     0       0        60       2     0       1
54   ...      0    0    0    0     0       0        15       2     1       1
55   ...      0    0    0    0     0       0        15       2     0       1
57   ...      0    0    0    0     0       0        75       1     0       1

[29 rows x 26 columns]
M
200.86666666666667
W
203.6206896551724
Способ 2
Sum m
[149 187 164 188 277 203 248 182 200 236 214 200 230 200 193 220 197 181
 217 223 221 149 203 187 167 189 208 197 195 201]
Sum w
[170 170 213 213 207 172 222 181 188 172 274 275 200 221 214 196 215 173
 171 264 210 220 175 178 213 201 170 181 246]
M
200.86666666666667
W
203.6206896551724
Median M
200.0
Median W
201.0

Признак duration - это время, которое студенты тратят на приход к первой паре. Найти студента из общаги с максимальным значением этого признака. Найти студента из общаги с минимальным значением этого признака. Поржать над этим!!!

In [4]:
h = df[(df['hostel'] == 1)]
#print(h)
d = h.sort_values(by='duration',ascending=False)
#print(d)
print("Дольше всех идет")
print(d.head(1))
print("Быстрее всех идет")
print(d.tail(1))

Дольше всех идет
   sex  age  growth       birth  EGEmath  EGEruss  EGEphis   s1   s2    s3  \
7    0   21     164  13.09.1994       68       95       50  3,5  3,5  3,25

    ...   yes3 yes4 yes5 yes6  yes7  hostel  duration  course  coin  stones
7   ...      0    0    0    0     0       1        60       3     1       1

[1 rows x 26 columns]
Быстрее всех идет
    sex  age  growth       birth  EGEmath  EGEruss  EGEphis   s1   s2   s3  \
31    0   20     156  05.03.1996       60       90       46  3,5  3,5  3,5

     ...   yes3 yes4 yes5 yes6  yes7  hostel  duration  course  coin  stones
31   ...      0    0    0    0     0       1        10       2     0       1

[1 rows x 26 columns]